#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

RECORDING="${RECORDING:-fixtures/canonical/feedback-recording.mp4}"
SOURCE_SHA256="f0b72e2f45e33166616e18293b1326be5fd8d1d8635a4e6a3770b516e9773fdc"
RECORDING_LABEL="canonical-six-case-v3"
BASELINE_FILE="${BASELINE_FILE:-manual-baseline.json}"
ISSUE_NUMBERS=()

# timed_start / timed_stop measure real elapsed seconds for one human task.
timed_start() { _TIMER_STARTED=$(date +%s); }
timed_stop() {
  local key="$1" now elapsed
  now=$(date +%s)
  elapsed=$((now - _TIMER_STARTED))
  (( elapsed < 1 )) && elapsed=1
  printf -v "$key" '%s' "$elapsed"
  printf '  %s✓ measured%s %s seconds\n' "$GREEN" "$RESET" "$elapsed"
}

banner "Manual baseline for the acceptance cycle"

stage "Confirm the destination and the recording"
say "The acceptance cycle compares the workflow against one honest human baseline"
say "for the same recording: you watch it, you write the equivalent Issues by hand."
say ""
say "Nothing here may be estimated. Every second recorded is a second you spent."
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "gh is required and must be authenticated."
  exit 1
fi
if [[ ! -f "$RECORDING" ]]; then
  warn "missing recording: $RECORDING"
  exit 1
fi
ask DEMO_REPOSITORY "Destination repository (owner/name):"
if [[ -z "${DEMO_REPOSITORY:-}" ]]; then
  warn "A destination repository is required."
  exit 1
fi
if ! gh repo view "$DEMO_REPOSITORY" >/dev/null 2>&1; then
  warn "cannot read $DEMO_REPOSITORY with the current gh account."
  exit 1
fi
note "recording: $RECORDING"
note "baseline output: $BASELINE_FILE"

stage "Watch the recording, timed"
say "Watch it the way a PM actually would: enough to understand every request."
say "You may pause or rewind. Do not skim; the number must be real."
warn "Press Enter to start the timer, then Enter again the moment you stop watching."
pause "Press Enter to start watching."
open_url "$(pwd)/$RECORDING"
timed_start
pause "Press Enter when you have finished watching."
timed_stop WATCH_SECONDS

stage "Write the three equivalent Issues by hand, timed"
say "Write the three Issues you would file from that recording: the CTA copy change,"
say "the mobile navbar overlap, and the contact submit anomaly."
say ""
say "Type a title, then the body one line at a time. End a body with a single dot."
warn "Do not paste anything generated by the agent. This is the human baseline."
pause "Press Enter to start the timer."
timed_start
for index in 1 2 3; do
  printf '\n  %s%sIssue %s of 3%s\n' "$BOLD" "$BLUE" "$index" "$RESET"
  ISSUE_TITLE=""
  while [[ -z "$ISSUE_TITLE" ]]; do
    printf '  %sTitle:%s ' "$BOLD" "$RESET"
    read -r ISSUE_TITLE || true
  done
  note "Body, one line at a time. A single dot on its own line ends it."
  ISSUE_BODY=""
  while true; do
    printf '  %s>%s ' "$DIM" "$RESET"
    read -r BODY_LINE || break
    [[ "$BODY_LINE" == "." ]] && break
    ISSUE_BODY+="$BODY_LINE"$'\n'
  done
  ISSUE_URL=$(gh issue create --repo "$DEMO_REPOSITORY" --title "$ISSUE_TITLE" --body "$ISSUE_BODY")
  ISSUE_NUMBERS+=("${ISSUE_URL##*/}")
  printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$ISSUE_URL"
done
timed_stop ISSUE_WRITING_SECONDS

stage "Close the baseline Issues"
say "The acceptance run refuses to start while any baseline Issue is open,"
say "and it never closes them for you."
for number in "${ISSUE_NUMBERS[@]}"; do
  gh issue close "$number" --repo "$DEMO_REPOSITORY" \
    --comment "Manual baseline for the Client Feedback Triage acceptance cycle; closed before the agent run." >/dev/null
  printf '  %s✓ closed%s #%s\n' "$GREEN" "$RESET" "$number"
done

stage "Record the measured baseline"
TOTAL_SECONDS=$((WATCH_SECONDS + ISSUE_WRITING_SECONDS))
say "Watching took $WATCH_SECONDS seconds; writing took $ISSUE_WRITING_SECONDS seconds."
say "Active human time is time you could not spend on anything else."
ask ACTIVE_HUMAN_SECONDS "Active human seconds [Enter accepts $TOTAL_SECONDS]:"
[[ -z "${ACTIVE_HUMAN_SECONDS:-}" ]] && ACTIVE_HUMAN_SECONDS="$TOTAL_SECONDS"
ask BASELINE_NOTES "One short note about how you measured it (optional):"
MEASURED_AT=$(date -Is)

WATCH_SECONDS="$WATCH_SECONDS" \
ISSUE_WRITING_SECONDS="$ISSUE_WRITING_SECONDS" \
ACTIVE_HUMAN_SECONDS="$ACTIVE_HUMAN_SECONDS" \
MEASURED_AT="$MEASURED_AT" \
BASELINE_NOTES="${BASELINE_NOTES:-}" \
SOURCE_SHA256="$SOURCE_SHA256" \
RECORDING_LABEL="$RECORDING_LABEL" \
BASELINE_FILE="$BASELINE_FILE" \
ISSUE_NUMBERS="${ISSUE_NUMBERS[*]}" \
python3 - <<'PY'
import json
import os
from pathlib import Path

numbers = [int(value) for value in os.environ["ISSUE_NUMBERS"].split()]
baseline = {
    "source_sha256": os.environ["SOURCE_SHA256"],
    "recording_label": os.environ["RECORDING_LABEL"],
    "equivalent_issue_count": len(numbers),
    "equivalent_issue_numbers": numbers,
    "watch_seconds": float(os.environ["WATCH_SECONDS"]),
    "issue_writing_seconds": float(os.environ["ISSUE_WRITING_SECONDS"]),
    "active_human_seconds": float(os.environ["ACTIVE_HUMAN_SECONDS"]),
    "measured_at": os.environ["MEASURED_AT"],
}
notes = os.environ.get("BASELINE_NOTES", "").strip()
if notes:
    baseline["notes"] = notes
path = Path(os.environ["BASELINE_FILE"])
path.write_text(json.dumps(baseline, indent=2) + "\n", encoding="utf-8")
print(f"  wrote {path}")
PY

finish
